### ISSUE TITLE
predict_model() got multiple values for argument 'samples'

### ISSUE THREAD

**Issue by shib0li** [AdamCobb/hamiltorch#11]
Hi Adam, 

When I run the notebook example of BNN at block 29, it shoots me this error. Any idea why this happens? Thanks.

**Comment by AdamCobb** [comment]
Hi Shibo Li,

Did you manage to solve the issue? I think I didn't update the notebook to the new code base, where the predict_model() needs the arguments for the data to be explicitly defined as a kwarg. e.g. "x=x_val, y=y_val", or if using a data loader "test_loader = test_loader".

Thanks,

Adam
