### ISSUE TITLE
torch.triangular_solve deprecated

### ISSUE THREAD

**Issue by ahenkes1** [AdamCobb/hamiltorch#19]
If you do some simple tutorial provided on your repo, this warning pops up:

`.local/lib/python3.10/site-packages/hamiltorch/samplers.py:146: UserWarning: torch.cholesky is deprecated in favor of torch.linalg.cholesky and will be removed in a future PyTorch release.
L = torch.cholesky(A)
should be replaced with
L = torch.linalg.cholesky(A)
and
U = torch.cholesky(A, upper=True)
should be replaced with
U = torch.linalg.cholesky(A).mH().
This transform will produce equivalent results for all valid (symmetric positive definite) inputs. (Triggered internally at ../aten/src/ATen/native/BatchLinearAlgebra.cpp:1615.)

UserWarning: torch.triangular_solve is deprecated in favor of torch.linalg.solve_triangularand will be removed in a future PyTorch release.
torch.linalg.solve_triangular has its arguments reversed and does not return a copy of one of the inputs.
X = torch.triangular_solve(B, A).solution
should be replaced with
X = torch.linalg.solve_triangular(A, B). (Triggered internally at ../aten/src/ATen/native/BatchLinearAlgebra.cpp:2115.)
  y = torch.triangular_solve(momentum.view(-1, 1), lower, upper=False, transpose=False, unitriangular=False)[0]`

It should be straight forward to update this, so no breaking errors happen during the next pyTorch release.

Best,
Alex

**Comment by AdamCobb** [comment]
Thanks very much for letting me know about this - I will have a look at this soon and test it out. I will then update the repo.
