### ISSUE TITLE
previous sample not appended upon rejection?

### ISSUE THREAD

**Issue by YilunZhou** [AdamCobb/hamiltorch#5]
If my understanding about HMC (and MH in general) is correct, if the new sample (i.e. proposal) is not accepted, the previous sample should be duplicated in the sample list. However, it looks like this duplication is not done. Specifically, on https://github.com/AdamCobb/hamiltorch/blob/74e190bad5ade95f395c8a2d003bdcd9bb3c1150/hamiltorch/samplers.py#L476 , upon acceptance, the new sample is appended the returned sample list, but upon rejection, nothing is done. Is this a mistake in the code?

**Comment by AdamCobb** [comment]
Hi,

Thanks for finding that. You are correct and I have now fixed the sampler. 

If you wanted to git pull and add a small comment like "# Ensure rejected sample is duplicated" above 
https://github.com/AdamCobb/hamiltorch/blob/9e5c6728fbf70c9cc23585fa7ee31d6a8bc877b8/hamiltorch/samplers.py#L481
and submit a pull request, then I can accept your pull request and you will be down as a contributor. That way I can ensure this fix is attributed to you (if that is something you would like).

Thanks once again!

Adam
